#1000
accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 10000    --batch-size 1 --eval-batch-size 1 --eval-steps 250 --learning-rate 4e-5 --warmup-steps 250 --checkpointing-steps 100    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name best_runs  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B --finetune-params embeddings   --unfreeze-params-steps 4000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 10000    --batch-size 1 --eval-batch-size 1 --eval-steps 250 --learning-rate 4e-5 --warmup-steps 250 --checkpointing-steps 100    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name best_runs  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B --finetune-params embeddings   --unfreeze-params-steps 4000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05

#100
accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 10000    --batch-size 1 --eval-batch-size 1 --eval-steps 250 --learning-rate 4e-5 --warmup-steps 250 --checkpointing-steps 100    --wandb efficient_tokenization  --dataset magpie-default-tokenized_100,magpie-translation-tokenized_100    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-100    --wandb-tags mixed,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 100 --experiment-name best_runs  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B --finetune-params embeddings   --unfreeze-params-steps 4000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 10000    --batch-size 1 --eval-batch-size 1 --eval-steps 250 --learning-rate 4e-5 --warmup-steps 250 --checkpointing-steps 100    --wandb efficient_tokenization  --dataset magpie-default-tokenized_100,magpie-translation-tokenized_100    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-100    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 100 --experiment-name best_runs  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B --finetune-params embeddings   --unfreeze-params-steps 4000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05

#10
accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 10000    --batch-size 1 --eval-batch-size 1 --eval-steps 250 --learning-rate 4e-5 --warmup-steps 250 --checkpointing-steps 100    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10,magpie-translation-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags mixed,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name best_runs  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B --finetune-params embeddings   --unfreeze-params-steps 4000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 10000    --batch-size 1 --eval-batch-size 1 --eval-steps 250 --learning-rate 4e-5 --warmup-steps 250 --checkpointing-steps 100    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10,magpie-translation-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name best_runs  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B --finetune-params embeddings   --unfreeze-params-steps 4000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05

# #0
accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 10000    --batch-size 1 --eval-batch-size 1 --eval-steps 250 --learning-rate 4e-5 --warmup-steps 250 --checkpointing-steps 100    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0,magpie-translation-tokenized_0    --task-name SFT    --wandb-tags SFT,baseline,first_last,extend_merge,new_runs,magpie  --eval-losses-to-track new_tokens,all --tokenizer-path meta-llama/Llama-3.2-3B    --num-new-tokens 0 --experiment-name base_model  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B --finetune-params embeddings   --unfreeze-params-steps 4000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 10000    --batch-size 1 --eval-batch-size 1 --eval-steps 250 --learning-rate 4e-5 --warmup-steps 250 --checkpointing-steps 100    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0,magpie-translation-tokenized_0    --task-name SFT    --wandb-tags SFT,baseline,lora,extend_merge,new_runs,magpie  --eval-losses-to-track new_tokens,all --tokenizer-path meta-llama/Llama-3.2-3B    --num-new-tokens 0 --experiment-name base_model  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B --finetune-params embeddings   --unfreeze-params-steps 4000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
