# # Baselines

# # # # just embeddings and first_last
# accelerate launch --num_processes 8 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,first_last,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,first_last,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,first_last,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 

# # # # just embeddings and lora
# accelerate launch --num_processes 8 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,lora,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,lora,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,lora,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05

# # # just embeddings and lora
# accelerate launch --num_processes 2 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,lora,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
# accelerate launch --num_processes 2 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,lora,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
# accelerate launch --num_processes 2 finetune.py  --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_0    --task-name SFT  --tokenizer-path meta-llama/Llama-3.2-3B-Instruct   --wandb-tags SFT,lora,baseline,new_runs,magpie --eval-losses-to-track all    --num-new-tokens 0 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer


# # Warmup tests

# # just embeddings and first_last
# accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 

# # just embeddings and lora
# accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05

# # # just embeddings and lora
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer

# # 10 tokens only
# # # just embeddings and first_last
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 

# # # just embeddings and lora
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05

# # # just embeddings and lora
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer


# #### MIXED DS
# # just embeddings and first_last
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 

# # just embeddings and lora
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05

# # # just embeddings and lora
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
# accelerate launch --num_processes 2 finetune.py --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000    --wandb-tags mixed,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 1000 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer





#######  This is added because there was a mistake above where we were unfreezing after only 10 steps
# 10 tokens only 
# # just embeddings and first_last
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,first_last,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze first_last  --reset-optimizer 

# # # just embeddings and lora
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05
# accelerate launch --num_processes 8 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze lora  --reset-optimizer  --lora-target-modules linear --lora-r 8 --lora-alpha 16 --lora-dropout 0.05

# # just embeddings and lora
accelerate launch --num_processes 2 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 100 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
accelerate launch --num_processes 2 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 250 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
accelerate launch --num_processes 2 finetune.py --run-lm-eval --limit 100 --total-batch-size 64 --max-train-steps 5000    --batch-size 1 --eval-batch-size 1 --eval-steps 100 --learning-rate 1e-5 --warmup-steps 500 --checkpointing-steps 250    --wandb efficient_tokenization  --dataset magpie-default-tokenized_10    --task-name mixed --embedding-init-strategy merge    --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10    --wandb-tags SFT,lora,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all    --num-new-tokens 10 --experiment-name warmup-tests  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-3B-Instruct --finetune-params embeddings   --unfreeze-params-steps 1000  --finetune-params-after-unfreeze full  --reset-optimizer
