# python train_tokenizer.py \
#     --raw-data-name magpie_pro_300k_filtered \
#     --dataset-source-path /cmlscratch/astein0/efficient_tokenization_for_inference/datasets \
#     --tokenized-data-name magpie_tokenized-llama3 \
#     --pre-tok-name empty \
#     --cont-or-start start \
#     --batch-size 1000 \
#     --added-tokens 1000 \
#     --tokenizer-path-old meta-llama/Llama-3.2-1B-Instruct \
#     --tokenizer-source huggingface \
#     --save-tokenized-data

# python shrink_tokenizer.py \
#     --old-tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000 \
#     --num-new-tokens-list 1,5,20,50,200,300,400,600,700,800,900

# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_0 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path meta-llama/Llama-3.2-1B-Instruct
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_1 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-1
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_5 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-5
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_10 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-10
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_20 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-20
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_50 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-50
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_100 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-100
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_200 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-200
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_300 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-300
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_400 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-400
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_500 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-500
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_600 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-600
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_700 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-700
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_800 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-800
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_900 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-900
# python data_preprocessing.py --raw-data-name magpie --dataset-path datasets/magpie_pro_300k_filtered --save-dataset-name tokenized_1000 --task default,translation --model meta-llama/Llama-3.2-1B-Instruct --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-genqa-math-empty-start-1000


# #64 bs, .00001 lr, merge, full finetune, 7000 steps
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_0 --task-name SFT --finetune-params full --embedding-init-strategy merge --tokenizer-path meta-llama/Llama-3.2-1B-Instruct --wandb-tags SFT,all_params_free,baseline,new_runs,magpie --eval-losses-to-track all --num-new-tokens 0 --experiment-name magpie_instruct  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-1B-Instruct
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_1,magpie-translation-tokenized_1 --task-name mixed --finetune-params full --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1 --wandb-tags mixed,all_params_free,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 1 --experiment-name magpie_instruct  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-1B-Instruct
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_10,magpie-translation-tokenized_10 --task-name mixed --finetune-params full --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10 --wandb-tags mixed,all_params_free,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 10 --experiment-name magpie_instruct  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-1B-Instruct
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_100,magpie-translation-tokenized_100 --task-name mixed --finetune-params full --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-100 --wandb-tags mixed,all_params_free,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 100 --experiment-name magpie_instruct  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-1B-Instruct
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000 --task-name mixed --finetune-params full --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000 --wandb-tags mixed,all_params_free,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 1000 --experiment-name magpie_instruct  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-1B-Instruct

accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_0 --task-name SFT --finetune-params embeddings --embedding-init-strategy merge --tokenizer-path meta-llama/Llama-3.2-1B-Instruct --wandb-tags SFT,all_params_free,baseline,new_runs,magpie,unfreeze1000 --eval-losses-to-track all --num-new-tokens 0 --experiment-name magpie_instruct  --benchmark-tasks ifeval --unfreeze-params-steps 1000 --model meta-llama/Llama-3.2-1B-Instruct
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_1,magpie-translation-tokenized_1 --task-name mixed --finetune-params embeddings --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1 --wandb-tags mixed,embeddings_free,unfreeze1000,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 1 --experiment-name magpie_instruct  --benchmark-tasks ifeval  --unfreeze-params-steps 1000 --model meta-llama/Llama-3.2-1B-Instruct
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_10,magpie-translation-tokenized_10 --task-name mixed --finetune-params embeddings --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-10 --wandb-tags mixed,embeddings_free,unfreeze1000,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 10 --experiment-name magpie_instruct  --benchmark-tasks ifeval  --unfreeze-params-steps 1000 --model meta-llama/Llama-3.2-1B-Instruct
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_100,magpie-translation-tokenized_100 --task-name mixed --finetune-params embeddings --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-100 --wandb-tags mixed,embeddings_free,unfreeze1000,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 100 --experiment-name magpie_instruct  --benchmark-tasks ifeval  --unfreeze-params-steps 1000 --model meta-llama/Llama-3.2-1B-Instruct
accelerate launch --num_processes 8 finetune.py --total-batch-size 64 --max-train-steps 2000 --batch-size 1 --eval-steps 100 --learning-rate 1e-5 --checkpointing-steps 250 --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000 --task-name mixed --finetune-params embeddings --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000 --wandb-tags mixed,embeddings_free,unfreeze1000,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 1000 --experiment-name magpie_instruct  --benchmark-tasks ifeval  --unfreeze-params-steps 1000 --model meta-llama/Llama-3.2-1B-Instruct

# test
# accelerate launch --num_processes 8 finetune.py --dry-run --total-batch-size 64 --max-train-steps 10 --batch-size 1 --eval-steps 5 --learning-rate 1e-5 --checkpointing-steps 1 --wandb efficient_tokenization  --dataset magpie-default-tokenized_1000,magpie-translation-tokenized_1000 --task-name mixed --finetune-params embeddings --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-1000 --wandb-tags mixed,embeddings_free,unfreeze1000,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 1000 --experiment-name magpie_instruct  --benchmark-tasks ifeval  --unfreeze-params-steps 1000 --model meta-llama/Llama-3.2-1B-Instruct

# accelerate launch --num_processes 2 finetune.py --dry-run --total-batch-size 64 --max-train-steps 10 --batch-size 1 --eval-steps 5 --learning-rate 1e-5 --checkpointing-steps 1 --wandb efficient_tokenization  --dataset magpie-default-tokenized_100,magpie-translation-tokenized_100 --task-name mixed --finetune-params full --embedding-init-strategy merge --tokenizer-path /cmlscratch/astein0/efficient_tokenization_for_inference/tokenizers/Llama-3.2-tokenizer-magpie_pro_300k_filtered-math-empty-start-100 --wandb-tags mixed,all_params_free,extend_merge,new_runs,magpie --eval-losses-to-track new_tokens,all --num-new-tokens 100 --experiment-name magpie_instruct  --benchmark-tasks ifeval --model meta-llama/Llama-3.2-1B-Instruct